name: Learn Kotlin 🧑‍🏫

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cancel-previous:
    name: Cancel Previous
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Build
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  test:
    name: "Test & Report"
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3.8.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Lint
        run: make lint
      - name: Test
        run: make test report
      - name: Report
        uses: codecov/codecov-action@v3.1.1
        with:
          files: ./build/reports/kover/result.xml
